bootstrap-servers-endpoints: ${KAFKA_BOOTSTRAP_SERVERS_ENDPOINTS:localhost:9092,localhost:9093,localhost:9094}
kafka:
  bootstrap-servers: ${bootstrap-servers-endpoints}
  topic:
    resources: resources
  consumer:
    concurrency: 3
retry:
  max:
    delay: 1000
    attempts: 3
server:
  port: 8083

